version: 2

models:
  - name: int_customer_first_order_date
    description: >
      Intermediate model that identifies each customer's first order date.
      Derives the earliest order date per customer and provides week- and
      month-level rollups for downstream customer analytics and lifecycle analysis.

    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
          - unique

      - name: customer_name
        description: "Full name of the customer"

      - name: first_order_date
        description: "The date of the customer's first recorded order"
        tests:
          - not_null

      - name: first_order_week
        description: "Week (date truncated) in which the customer's first order occurred"

      - name: first_order_month
        description: "Month (date truncated) in which the customer's first order occurred"

  - name: int_customer_last_order_date
    description: >
      Intermediate model that identifies each customer's most recent order date.
      Derives the latest order date per customer and provides week- and
      month-level rollups for downstream customer recency and retention analysis.

    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
          - unique

      - name: customer_name
        description: "Full name of the customer"

      - name: last_order_date
        description: "The date of the customer's most recent recorded order"
        tests:
          - not_null

      - name: last_order_week
        description: "Week (date truncated) in which the customer's most recent order occurred"

      - name: last_order_month
        description: "Month (date truncated) in which the customer's most recent order occurred"

  - name: int_customer_order_amounts
    description: >
      Intermediate model that aggregates customer-level order revenue across
      multiple time horizons. Provides lifetime, year-to-date, quarter-to-date,
      month-to-date, and rolling 30/60/90-day sales metrics for downstream
      revenue, segmentation, and lifecycle analysis.

    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
          - unique

      - name: customer_name
        description: "Full name of the customer"

      - name: lifetime_customer_sales
        description: "Total sales generated by the customer across all time"
        tests:
          - not_null

      - name: ytd_customer_sales
        description: "Total sales generated by the customer in the current calendar year"

      - name: qtd_customer_sales
        description: "Total sales generated by the customer in the current calendar quarter"

      - name: mtd_customer_sales
        description: "Total sales generated by the customer in the current calendar month"

      - name: l30_days_sales
        description: "Total sales generated by the customer in the last 30 days"

      - name: l60_days_sales
        description: "Total sales generated by the customer in the last 60 days"

      - name: l90_days_sales
        description: "Total sales generated by the customer in the last 90 days"
      
  - name: int_customer_order_volume
    description: >
      Intermediate model that aggregates customer-level order volume across
      multiple time horizons. Provides lifetime, year-to-date, quarter-to-date,
      month-to-date, and rolling 30/60/90-day unit volume metrics for downstream
      demand, frequency, and customer activity analysis.

    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
          - unique

      - name: customer_name
        description: "Full name of the customer"

      - name: lifetime_customer_order_volume
        description: "Total number of units ordered by the customer across all time"
        tests:
          - not_null

      - name: ytd_customer_order_volume
        description: "Total number of units ordered by the customer in the current calendar year"

      - name: qtd_customer_order_volume
        description: "Total number of units ordered by the customer in the current calendar quarter"

      - name: mtd_customer_order_volume
        description: "Total number of units ordered by the customer in the current calendar month"

      - name: l30_days_order_volume
        description: "Total number of units ordered by the customer in the last 30 days"

      - name: l60_days_order_volume
        description: "Total number of units ordered by the customer in the last 60 days"

      - name: l90_days_order_volume
        description: "Total number of units ordered by the customer in the last 90 days"

  - name: int_customer_profit
    description: >
      Intermediate model that aggregates customer-level profit metrics.
      Calculates lifetime profit as well as year-to-date, quarter-to-date,
      month-to-date, and recent rolling-period profit for customer profitability analysis.

    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null
          - unique

      - name: customer_name
        description: "Full name of the customer"

      - name: lifetime_customer_profit
        description: "Total profit generated by the customer across all historical orders"
        tests:
          - not_null

      - name: ytd_customer_profit
        description: "Total profit generated by the customer year-to-date"

      - name: qtd_customer_profit
        description: "Total profit generated by the customer quarter-to-date"

      - name: mtd_customer_profit
        description: "Total profit generated by the customer month-to-date"

      - name: l30_days_profit
        description: "Total profit generated by the customer in the last 30 days"

      - name: l60_days_profit
        description: "Total profit generated by the customer in the last 60 days"

      - name: l90_days_profit
        description: "Total profit generated by the customer in the last 90 days"