version: 2

models:
  - name: stg_superstore
    description: "Staging model for the Sample Superstore dataset. Prepares raw CSV data for downstream analysis."
    columns:
      - name: order_id
        description: "Unique identifier for each order"
        tests:
          - unique
          - not_null

      - name: order_date
        description: "The date the order was placed"
        tests:
          - not_null

      - name: ship_date
        description: "The date the order was shipped"
        tests:
          - not_null

      - name: ship_mode
        description: "The shipping mode selected for the order"

      - name: customer_id
        description: "Unique identifier for each customer"
        tests:
          - not_null

      - name: customer_name
        description: "Full name of the customer"

      - name: segment
        description: "Customer segment (Consumer, Corporate, Home Office)"

      - name: country
        description: "Country of the customer"

      - name: city
        description: "City of the customer"

      - name: state
        description: "State of the customer"

      - name: postal_code
        description: "Postal code of the customer"

      - name: region
        description: "Region of the customer"

      - name: product_id
        description: "Unique identifier for each product"

      - name: category
        description: "High-level product category"

      - name: sub_category
        description: "Subcategory of the product"

      - name: product_name
        description: "Name of the product"

      - name: sales
        description: "Revenue from the product sale"

      - name: quantity
        description: "Number of units sold"

      - name: discount
        description: "Discount applied to the order"

      - name: profit
        description: "Profit from the sale"